name: Docker Deploy

on:
  push:
    branches:
      - main
      - feature

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # PRODUCTION DEPLOY (main)
      
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        shell: powershell
        run: |
          Write-Host "Deploying PRODUCTION..."

          # Stop old container
          $container = docker ps -a --format "{{.Names}}" | Select-String "^node-app-prod$"

          if ($container) {
            docker stop node-app-prod
            docker rm node-app-prod
          }

          # Remove old image
          $image = docker images --format "{{.Repository}}" | Select-String "^node-app-prod-image$"

          if ($image) {
            docker rmi node-app-prod-image
          }

          # Build image
          docker build -t node-app-prod-image .

          # Run container
          docker run -d `
            --name node-app-prod `
            -p 5000:5000 `
            node-app-prod-image

      # STAGING DEPLOY (feature)
      
      - name: Deploy Staging
        if: github.ref == 'refs/heads/feature'
        shell: powershell
        run: |
          Write-Host "Deploying STAGING..."

          # Stop old container
          $container = docker ps -a --format "{{.Names}}" | Select-String "^node-app-stage$"

          if ($container) {
            docker stop node-app-stage
            docker rm node-app-stage
          }

          # Remove old image
          $image = docker images --format "{{.Repository}}" | Select-String "^node-app-stage-image$"

          if ($image) {
            docker rmi node-app-stage-image
          }

          # Build image
          docker build -t node-app-stage-image .

          # Run container
          docker run -d `
            --name node-app-stage `
            -p 5001:5000 `
            node-app-stage-image

      - name: Show running containers
        shell: powershell
        run: docker ps
