name: Local Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old container
        shell: powershell
        run: |
          $container = docker ps -a --format "{{.Names}}" | Select-String "^node-app$"

          if ($container) {
            docker stop node-app
            docker rm node-app
          }
          else {
            Write-Host "Container node-app does not exist"
          }

      - name: Remove old image
        shell: powershell
        run: |
          $image = docker images --format "{{.Repository}}" | Select-String "^node-app-image$"

          if ($image) {
            docker rmi node-app-image
          }
          else {
            Write-Host "Image node-app-image does not exist"
          }

      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t node-app-image .

      - name: Run Docker container
        shell: powershell
        run: |
          docker run -d `
            --name node-app `
            -p 5000:5000 `
            node-app-image

      - name: Show running containers
        shell: powershell
        run: docker ps
